---
eval: false
engine: knitr
---

# System requirements

## Main system requirements 

- Ubuntu 18.04
- R 4.3.0, Bioconducctor 3.17
- Python 3.7

## Non-standard hardware requirements

A RTX 2080 Ti GPU was used to improve the training speed of convolutional neural neworks. 

## Data processing softwares

### Processing tools

- Bowtie2 2.4.5
- samtools 1.9
- deeptools 2.26.0
- bedtools 2.29.1
- MACS2 2.2.7.1
- seqkit 2.2.0
- Keras
- Tensorflow

### Processing workflow managers 

Most sequencing data was processed with [tinyMapper 0.11.3-0.12.14](https://github.com/js2264/tinyMapper).  
Hi-C data was processed with [hicstuff 3.1.2](https://github.com/koszullab/hicstuff) and [Chromosight 1.4.1](https://github.com/koszullab/chromosight).

## Relevant R packages 

Main R packages used in this study are listed below. All versions are 
bound to Bioconductor 3.17 unless specifically mentioned. 

- S4Vectors
- GenomicRanges
- GenomicAlignments
- Biostrings
- rtracklayer
- plyranges
- ggplot2
- Repliscope 1.1.1
- HiCExperiment 
- HiContacts 

## Relevant python packages 

Main python packages used in this study are listed below: 

- cooler 0.8.7-0.8.11
- hicstuff 3.1.2
- Chromosight 1.4.1
- cooltools 0.5.1 
- pysam 0.16.0.1
- pyBigWig 3.8.3

## Installation guide

R 4.3.0 was installed from binaries provided by Posit/RStudio as follows: 

```{sh}
#| eval: false
curl -O https://cdn.rstudio.com/r/ubuntu-2004/pkgs/r-4.3.0_1_amd64.deb
sudo gdebi r-4.3.0_1_amd64.deb
```

Installation for all the other dependencies was managed through `conda` environment manager. 

```{sh}
#| eval: false
# packages in environment at /home/rsg/miniconda3/envs/tm:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
babel                     2.11.0             pyhd8ed1ab_0    conda-forge
bedtools                  2.30.0               h468198e_3    bioconda
binutils_impl_linux-64    2.36.1               h193b22a_2    conda-forge
binutils_linux-64         2.36                hf3e587d_10    conda-forge
bioframe                  0.3.3              pyhdfd78af_0    bioconda
biopython                 1.79             py37h540881e_2    conda-forge
blas                      1.1                    openblas    conda-forge
bokeh                     2.4.3            py37h89c1867_0    conda-forge
bowtie2                   2.5.0            py37hb24965f_0    bioconda
brotli                    1.0.9                h166bdaf_8    conda-forge
brotli-bin                1.0.9                h166bdaf_8    conda-forge
brotlipy                  0.7.0           py37h540881e_1004    conda-forge
bwa                       0.7.17               h7132678_9    bioconda
bwidget                   1.9.14               ha770c72_1    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2023.05.30           h06a4308_0
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.16.0            h18b612c_1001    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py37h43b0acd_1    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3            py37h89c1867_0    conda-forge
cloudpickle               2.2.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
cooler                    0.8.11             pyh5e36f6f_1    bioconda
coreutils                 8.25                          1    bioconda
cryptography              38.0.2           py37h38fbfac_1    conda-forge
curl                      7.87.0               h6312ad2_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.12.0           py37h540881e_0    conda-forge
dask                      2021.10.0          pyhd8ed1ab_0    conda-forge
dask-core                 2021.10.0          pyhd8ed1ab_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
deeptools                 3.5.1                      py_0    bioconda
deeptoolsintervals        0.1.9            py37h8902056_4    bioconda
dill                      0.3.6              pyhd8ed1ab_1    conda-forge
distributed               2021.10.0        py37h06a4308_0
docopt                    0.6.2                      py_1    conda-forge
docutils                  0.19             py37h89c1867_0    conda-forge
expat                     2.5.0                h27087fc_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.1               hc2a2eb6_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.38.0           py37h540881e_0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
fribidi                   1.0.10               h516909a_0    conda-forge
fsspec                    2022.11.0          pyhd8ed1ab_0    conda-forge
gcc_impl_linux-64         11.2.0              h82a94d6_16    conda-forge
gcc_linux-64              11.2.0              h39a9532_10    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gfortran_impl_linux-64    11.2.0              h7a446d4_16    conda-forge
gfortran_linux-64         11.2.0              h777b47f_10    conda-forge
glib                      2.74.1               h6239696_0    conda-forge
glib-tools                2.74.1               h6239696_0    conda-forge
graphite2                 1.3.14               h295c915_1
gst-plugins-base          1.14.0               h8213a91_2
gstreamer                 1.14.0               h28cd5cc_2
gxx_impl_linux-64         11.2.0              h82a94d6_16    conda-forge
gxx_linux-64              11.2.0              hacbe6df_10    conda-forge
h5py                      3.7.0           nompi_py37hf1ce037_101    conda-forge
harfbuzz                  4.3.0                hd55b92a_0
hdf5                      1.12.2          nompi_h2386368_101    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
hicstuff                  3.1.5              pyhdfd78af_1    bioconda
htslib                    1.17                 h6bc39ce_0    bioconda
icu                       58.2              hf484d3e_1000    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4           py37h89c1867_0    conda-forge
java-jdk                  8.0.112                       1    bioconda
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
k8                        0.2.5                hd03093a_2    bioconda
kernel-headers_linux-64   2.6.32              he073ed8_15    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4            py37h7cecad7_0    conda-forge
krb5                      1.20.1               hf9c8cef_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libaec                    1.0.6                h9c3ff4c_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_8    conda-forge
libbrotlidec              1.0.9                h166bdaf_8    conda-forge
libbrotlienc              1.0.9                h166bdaf_8    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcurl                   7.87.0               h6312ad2_0    conda-forge
libdeflate                1.13                 h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-devel_linux-64     11.2.0              h0952999_16    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libglib                   2.74.1               h7a41b64_0    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libhwloc                  2.8.0                h32351e8_1    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnghttp2                1.51.0               hdcd2b5c_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsanitizer              11.2.0              he4da1e4_16    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-devel_linux-64  11.2.0              h0952999_16    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtiff                   4.2.0                hf544144_3    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.15                 h7f8727e_0
libxml2                   2.9.14               h74e7548_0
libzlib                   1.2.13               h166bdaf_4    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
macs2                     2.2.7.1          py37h8902056_5    bioconda
make                      4.3                  hd18ef5c_1    conda-forge
markupsafe                2.1.1            py37h540881e_1    conda-forge
matplotlib                3.5.3            py37h89c1867_2    conda-forge
matplotlib-base           3.5.3            py37hf395dca_2    conda-forge
mawk                      1.3.4                hec16e2b_5    bioconda
minimap2                  2.24                 h7132678_1    bioconda
msgpack-python            1.0.4            py37h7cecad7_0    conda-forge
multiprocess              0.70.14          py37h540881e_0    conda-forge
munkres                   1.0.7                      py_1    bioconda
mysql-connector-c         6.1.11            h6eb9d5d_1007    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.21.6           py37h976b520_0    conda-forge
numpydoc                  1.5.0              pyhd8ed1ab_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openblas                  0.3.21          pthreads_h320a7e8_3    conda-forge
openjdk                   8.0.112          zulu8.19.0.1_3    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1u               hd590300_0    conda-forge
packaging                 22.0               pyhd8ed1ab_0    conda-forge
pairix                    0.3.7            py37ha26db04_4    bioconda
pairtools                 1.0.2            py37h9f12aac_0    bioconda
pandas                    1.3.5            py37he8f5f7f_0    conda-forge
pango                     1.50.7               hbd2fdc8_0    conda-forge
partd                     1.3.0              pyhd8ed1ab_0    conda-forge
pbgzip                    2016.08.04           h67092d7_3    bioconda
pcre2                     10.37                hc3806b6_1    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pillow                    8.2.0            py37h4600e1f_1    conda-forge
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
plotly                    5.11.0             pyhd8ed1ab_1    conda-forge
psutil                    5.9.3            py37h540881e_0    conda-forge
py2bit                    0.3.0            py37h8902056_6    bioconda
pybigwig                  0.3.18           py37hdc12a6d_2    bioconda
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyfaidx                   0.7.1              pyh5e36f6f_0    bioconda
pyfastx                   0.8.4            py37ha26db04_1    bioconda
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 22.1.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.6.0           py37h13b7fb3_1008    conda-forge
pysam                     0.20.0           py37hee149a5_0    bioconda
pysocks                   1.7.1            py37h89c1867_5    conda-forge
python                    3.7.12          hb7a2778_100_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.7                     3_cp37m    conda-forge
pytz                      2022.7             pyhd8ed1ab_0    conda-forge
pyvcf3                    1.0.3              pyhdfd78af_0    bioconda
pyyaml                    6.0              py37h540881e_4    conda-forge
qt                        5.6.3                h8bf5577_3
r-base                    4.2.0                h1ae530e_0
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
samtools                  1.17                 h00cdaf9_0    bioconda
scikit-learn              1.0.2            py37hf9e9bfc_0    conda-forge
scipy                     1.7.3            py37hf2a6cf1_0    conda-forge
setuptools                59.8.0           py37h89c1867_1    conda-forge
simplejson                3.17.6           py37h540881e_1    conda-forge
sip                       4.18.1          py37hf484d3e_1000    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sphinx                    5.3.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
sqlite                    3.40.0               h4ff8645_0    conda-forge
star                      2.7.10b              h6b7c446_1    bioconda
sysroot_linux-64          2.12                he073ed8_15    conda-forge
tbb                       2021.7.0             h924138e_1    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
tenacity                  8.1.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tktable                   2.10                 hb7b940f_3    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2              py37h540881e_0    conda-forge
tree                      2.0.0                h7f98852_0    conda-forge
typing-extensions         4.4.0                hd8ed1ab_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
ucsc-bedgraphtobigwig     357                           0    bioconda
ucsc-bigwigtowig          377                  ha8a8165_3    bioconda
unicodedata2              14.0.0           py37h540881e_1    conda-forge
urllib3                   1.26.13            pyhd8ed1ab_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zict                      2.2.0              pyhd8ed1ab_0    conda-forge
zipp                      3.11.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge
```

The installation of all these standard softwares takes less than 15 minutes on a standard laptop. 
