---
eval: false
engine: knitr
---

Code and notes for the manuscript L. Meneu et al., 2024: 
*"Sequence-dependent activity and compartmentalization of foreign DNA in a eukaryotic nucleus"*.

Browse each `.qmd` file independently or open the `docs/index.html` to 
view the rendered HTML online book. 

## Instructions for use {-}

All the source code used to analyse and visualize data during this project is included here. 
However, local paths for processed data (e.g. genomic tracks, peak sets, bam files, etc.) are hard-coded. To replicate exactly the provided notebooks, processed data can be downloaded from GEO and the corresponding paths should be replaced. 

All sequencing data and processed files are available from GEO: 
[GSE217022](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE217022)

## Source code  {-}

- Source code for sequencing data processing is provided in [Processing section](01.Processing.qmd);
- Source code for every panel of each main Figure (along with the corresponding Extended Data Figures) is provided in a separate `.qmd` file: 
  - [Figure 1, Extended Data Figure 1, 2](02.Analysis-Figure-01.qmd)
  - [Figure 2, Extended Data Figure 3](03.Analysis-Figure-02.qmd)
  - [Figure 3, Extended Data Figure 4](04.Analysis-Figure-03.qmd)
  - [Figure 4, Extended Data Figure 5](05.Analysis-Figure-04.qmd)
  - [Figure 5, Extended Data Figure 6](06.Analysis-Figure-05.qmd)
